version: '3'
services:
  web:
    build: "."
    container_name: predict-coagulants
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./payload:/app/payload
    expose:
      - "8000"
    command: python /app/app.py

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web
